- go.mod
- types/anonaddress/acmeAddress.go
- types/anonaddress/acmeAddress_test.go
Updates to how we can create anonymous token chains.
> updated code for encoding public keys to an anonymous token chain identifiers

- router/proxy.go
- Added support for query params in Accumulate URLs into proxy
> support for query params in proxy

- blockchain/tendermint/abci-bvc.go
Fixes [AC-303](https://accumulate.atlassian.net/browse/AC-303)
> Fix node crash

- blockchain/validator/Node.go
- cmd/accumulated/cmd_run.go
- internal/relay/helper.go
- internal/relay/relay.go
- router/jsonrpc.go
- router/jsonrpc_test.go
- router/query.go
> Cleanup 3/6: networks.Bouncer => internal/relay.Relay

- cmd/accumulated/cmd_loadtest.go
I put a check in the wrong place
> Loadtest fix

- cmd/accumulated/cmd_run.go
- internal/abci/accumulator.go
> Remove kvstore database

- README.md
- cmd/accumulated/cmd_loadtest.go
- internal/node/init.go
- Allow specifying the network name or number
- Add instructions to the README
> Improve load test experience

- cmd/accumulated/cmd_run.go
- internal/relay/helper.go
- router/jsonrpc_test.go
- router/utils_test.go
@bunfield ~~So far I've fixed a number of bugs (generally caused by me). It still isn't 100%, but this makes it less broken.~~ The tests succeed now.
> Fix JSON RPC tests

- .github/workflows/merge.yml
- .github/workflows/validate.yml
More details on [AC-345](https://accumulate.atlassian.net/browse/AC-345). Blocks PRs unless the base/target is `develop`.
> Only allow merge into develop

- router/query.go
did a workaround to the issue.  there is an underlying issue that I need to address with pending transactions that i will open up as a new task.
> Ac 200 cli queryfix

- cmd/accumulated/cmd_run.go
- config/config.go
- config/config_test.go
- internal/api/jsonrpc.go
- internal/api/jsonrpc_test.go
- internal/api/utils_test.go
- internal/node/init.go
Move accumulate-specific config in `config/accumulate.toml`, out of `config/config.toml`
> Separate Accumulate config from Tendermint config

- cmd/accumulated/cmd_init.go
- cmd/accumulated/cmd_run.go
- cmd/accumulated/cmd_testnet.go
- config/config.go
- config/config_test.go
- internal/api/jsonrpc_test.go
- internal/api/utils_test.go
- internal/relay/helper.go
Make TX relay configurable instead of hard-coded to EastXeons.
> Don't hard-code TX relay

- .github/workflows/validate.yml
- cmd/accumulated/cmd_init.go
- cmd/accumulated/cmd_loadtest.go
- cmd/accumulated/cmd_testnet.go
- config/config.go
Adds CI tests that init, run, and load test nodes
> Run CLI integration tests in CI

- types/api/transactions/gentransaction.go
Replace panic with directly returning an error in GenTransaction Marshal and UnMarshal. Remove defer/recover.
> Don't panic in GenTransaction un/marshal

- internal/api/jsonrpc_test.go
- internal/api/utils2_test.go
- internal/api/utils_test.go
- internal/chain/anonymous_token_test.go
- internal/node/node.go
- internal/node/node_test.go
- internal/testing/node.go
> Test node creation

- internal/api/utils_test.go
- internal/node/node_test.go
- internal/testing/node.go
Hopefully this fixes tests that are flaky on macos
> test: always cleanup node creation

- docs/URL.md
Document what we talked about so we don't trip up Jason with fun surprises
> Document URL specification

- internal/abci/e2e_statedb_test.go
- internal/abci/e2e_test.go
- internal/chain/add_credits.go
- internal/chain/chain.go
- internal/chain/synthetic_deposit_credits.go
- internal/testing/state.go
- types/helpers.go
Implement transaction processing for adding credits to a multi sig
> Implement add credits

- internal/api/query.go
- fixed scope of unmarshal for query
> fixed scope of unmarshalChainState

- docs/URL.md
- protocol/protocol.go
https://accumulate.atlassian.net/browse/AC-419
> Don't include token URL in checksum

- types/state/StateDB.go
Minimal changes required to fix the latest consistency bug
> fix: consistency bug

- internal/api/jsonrpc.go
- make transaction id 0000000000000000000000000000000 to avoid confusion
> clarify txid in faucet transaction

- internal/api/query.go
- internal/api/unmarshal.go
- internal/chain/executor.go
- types/api/APIRequests.go
- types/state/Transaction.go
- added status to pending chain 
- added pending chain info to transaction queries.
> added status to pending chain and added more detail to query

- .github/workflows/validate.yml
- internal/api/jsonrpc_test.go
- internal/node/e2e_test.go
- internal/node/node_test.go
- internal/testing/go_version_1.16.go
- internal/testing/go_version_1.17.go
The tests appear to be working.
> test: remove skip

- internal/node/node.go
- internal/relay/helper.go
- networks/getaddr.go
Also, fail if the RPC error isn't connection refused
> fix: resolve named networks

- debug/faucet_test.go
- internal/abci/e2e_statedb_test.go
- internal/abci/e2e_test.go
- internal/abci/utils_test.go
- internal/api/jsonrpc.go
- internal/api/jsonrpc_test.go
- internal/api/query.go
- internal/api/utils_test.go
- internal/chain/executor.go
- internal/chain/state.go
- internal/chain/synthetic_create_chain.go
- internal/logging/test.go
- internal/node/node_test.go
- internal/node/utils_test.go
- internal/testing/node.go
- internal/testing/state.go
- protocol/types.yml
- protocol/types_gen.go
- smt/storage/badger/db.go
- smt/storage/database/manager.go
- smt/storage/keys.go
- smt/storage/memory/db.go
- types/api/APIRequests.go
- types/query_types.go
- types/state/StateDB.go
- types/state/index.go
- Adds methods for writing indicies to the key-value DB
- Updates Synthetic Create Chain to add directory index entries
- Adds API for querying directory indices
> ADI directory entries

- internal/chain/executor.go
The second parameter of GetRange is an index rather than a length.  Foxed
> Fix the call to GetRange

- go.mod
- go.sum
- internal/api/jsonrpc_test.go
- internal/api/utils2_test.go
https://github.com/tendermint/tendermint/issues/7185
> fix: tendermint replay hang

- internal/node/node.go
Retries RPC connection to other nodes for more error cases. Makes it less likely that a node will fail to start due to a spurrious error.
> fix: make RPC wait error check more lax

- cmd/accumulated/program.go
- config/config.go
- internal/api/jsonrpc.go
- internal/api/utils_test.go
- internal/node/e2e_test.go
- internal/node/node.go
- internal/node/utils_test.go
Add a config option to enable TX subscription, and leave it disabled by default.
> feat: disable TX subscription by default

- internal/api/jsonrpc.go
- types/api/APIRequests.go
Add a JSON RPC API call that returns the Accumulate version
> feat: JSON RPC API call for version

- cmd/cli/cmd/account.go
Convert accounts in the `anon` bucket to `label` and `keys`
> Restore old CLI accounts

- internal/api/query.go
- types/api/APIRequests.go
Include the transaction ID of each TX in TX history
> feat: include txid in TX history

- internal/api/jsonrpc.go
- internal/api/jsonrpc_errors.go
Implement a specific error code for not-a-lite-account and not-an-acme-account
> feat: error codes for faucet

- internal/api/jsonrpc_test.go
- internal/api/query.go
- internal/api/unmarshal.go
- types/state/Transaction.go
Update query transaction handling so that the genesis TX doesn't cause errors
> fix: handling of genesis TX

- protocol/keys.go
- protocol/protocol.go
- protocol/protocol_test.go
- protocol/types_gen.go
- protocol/utils.go
- types/anonaddress/acmeAddress_test.go
Added some validation rules to the Simple Token Address creation
Added a test
Enabled a test to old anonymous address generation
> Added some tests to Simple Token Addresses

- go.mod
- go.sum
- internal/node/e2e_test.go
God I love these Tendermint bugs /s
> fix: actually fix the bug for real this time

- cmd/accumulated/program.go
- cmd/cli/cmd/util.go
- internal/abci/accumulator.go
- internal/api/jsonrpc.go
- internal/api/jsonrpc_test.go
- internal/chain/executor.go
- internal/logging/types.go
- internal/testing/app_client.go
- internal/testing/load.go
- internal/testing/state.go
- types/api/transactions/SignatureInfo.go
- types/api/transactions/gentransaction_test.go
- types/state/StateDB.go
- types/state/index.go
> Fix consensus error when you restart one node but not the other

- cmd/cli/cmd/account.go
- cmd/cli/cmd/key.go
- correct error check if no data found
- added print-out confirmation for mnemonic.
> minor fix to key import

- internal/api/jsonrpc.go
Add some comments so new developers don't have to spend so much time figuring out what's happening
> chore: comments for the API

- cmd/cli/cmd/account.go
- go.mod
- go.sum
`cli account qr acc://e7ebdb79f46fd8f902f38b9bc8bc0d14906139a024cb1836/ACME`
> feat(cli): print QR for lite account

- internal/api/v2/README.md
- internal/api/v2/dispatch_test.go
- internal/api/v2/error.go
- internal/api/v2/jrpc.go
- internal/api/v2/jrpc_execute.go
- internal/api/v2/types.go
- internal/api/v2/types.yml
- internal/api/v2/types_gen.go
- types/api/Token.go
Execute and dispatch/batch implementation for API v2
> API v2: Execute (3/4)

- .gitlab-ci.yml
- cmd/accumulated/cmd_init.go
- cmd/accumulated/cmd_loadtest.go
- internal/api/utils_test.go
- internal/node/node_test.go
- internal/testing/node.go
- networks/getaddr.go
- networks/networks.go
- scripts/management/tmux-devnet.sh
- Rename `networks.Network` to `Subnet` (BVC)
- Add `Network` as a set of subnets
- Separate BVCs by network (testnet, devnet, etc)
- Deploy to CI instead of OG testnet
> ci: deploy to devnet

- types/state/Object.go
merkle hash in query response(AC-515)
> merkle root value in query fix(AC-515)

- cmd/accumulated/program.go
- config/config.go
- internal/api/v2/jrpc.go
- internal/api/v2/jrpc_execute.go
- internal/api/v2/query_direct.go
- internal/api/v2/types.yml
- internal/api/v2/types_gen.go
- internal/node/init.go
- Update `accumulated` to use the new API
- Drop support for wait-for-deliver in the new API
> Integrate API v2

- cmd/cli/cmd/adi.go
- fixed cli command-line arguments for keybook/page when creating an adi.
> fix for ignoring key page setting

- internal/abci/e2e_proofs_test.go
- internal/abci/utils_test.go
Add a test so Paul can add cryptographic proof verification.
No functional changes.
> test: prepare test for merkle proofs

- internal/abci/e2e_proofs_test.go
This fixes a compile error. No functional changes.
> test: fix compile error caused by refactor

- smt/managed/merklemanager.go
- smt/managed/receipt.go
- smt/managed/receipt_test.go
> test: fix SMT receipt tests

- .gitlab-ci.yml
- cmd/cli/cmd/util.go
Add basic validation to CI via CLI
> ci: basic validation

- scripts/cli_adi_create_account.sh
- scripts/cli_key_generate.sh
- scripts/test_case_1.1.sh
- scripts/test_case_2.1.sh
- scripts/test_case_2.2.sh
- scripts/test_case_2.3.sh
- scripts/test_case_2.4.sh
- scripts/test_case_2.5.sh
- scripts/test_case_2.6.sh
- scripts/test_case_2.7.sh
- scripts/test_case_3.1.sh
- scripts/test_case_3.2.sh
- scripts/test_case_3.3.sh
- scripts/test_case_3.4.sh
- scripts/test_case_5.2.sh
Adding test case 4.1 script and fixed some issues with the other scripts
> Ac 558 create unbound key page

- scripts/cli_adi_create_account.sh
- scripts/cli_key_generate.sh
- scripts/test_case_1.1.sh
- scripts/test_case_2.1.sh
- scripts/test_case_2.2.sh
- scripts/test_case_2.3.sh
- scripts/test_case_2.4.sh
- scripts/test_case_2.5.sh
- scripts/test_case_2.6.sh
- scripts/test_case_2.7.sh
- scripts/test_case_3.1.sh
- scripts/test_case_3.2.sh
- scripts/test_case_3.3.sh
- scripts/test_case_3.4.sh
- scripts/test_case_5.2.sh
> Added test case 4.2 script

- internal/abci/accumulator_test.go
- internal/mock/abci/abci.go
Regenerate ABCI mock to fix CI failures
> fix: regenerate abci mock

- internal/abci/abci.go
- internal/abci/accumulator.go
- internal/abci/accumulator_test.go
- internal/abci/e2e_proofs_test.go
- internal/abci/e2e_statedb_test.go
- internal/abci/e2e_test.go
- internal/abci/utils_test.go
- internal/api/jsonrpc_test.go
- internal/chain/executor.go
- internal/chain/synthetic_chain_create_test.go
- internal/chain/update_key_page_test.go
- internal/chain/withdraw_tokens_test.go
- internal/cmd/gentypes/main.go
- internal/cmd/gentypes/types.go
- internal/encoding/utils.go
- internal/mock/abci/abci.go
- protocol/codes.go
- smt/managed/merklemanager.go
- types/state/StateDB.go
- types/state/stateTxn.go
- types/state/types.go
- types/state/types.yml
- types/state/types_gen.go
Implement a basic BVN anchor chain.
Run `TestAnchorChain` in `internal/abci/e2e_test.go`.
> feat: implement basic BVN anchor chain

- cmd/cli/cmd/tx.go
- scripts/validate.sh
Add checks to the validation script to actually verify that things do what they're supposed to.
> More validation

- .gitlab-ci.yml
Fix the validation CI job by installing `jq`.
> ci: install jq

- scripts/cli_adi_create_account.sh
- scripts/cli_key_generate.sh
- scripts/test_case_1.1.sh
- scripts/test_case_2.1.sh
- scripts/test_case_2.2.sh
- scripts/test_case_2.3.sh
- scripts/test_case_2.4.sh
- scripts/test_case_2.5.sh
- scripts/test_case_2.6.sh
- scripts/test_case_2.7.sh
- scripts/test_case_3.1.sh
- scripts/test_case_3.2.sh
- scripts/test_case_3.3.sh
- scripts/test_case_3.4.sh
- scripts/test_case_5.2.sh
> Added test case 4.4 script

- scripts/README.md
- scripts/fcttest.sh
- scripts/test_case_4.1.sh
- scripts/test_case_4.2.sh
- scripts/test_case_4.3.sh
- scripts/test_case_4.4.sh
> Updating scripts

- scripts/README.md
- scripts/cli_adi_create_account.sh
- scripts/cli_key_generate.sh
- scripts/fcttest.sh
- scripts/test_case_1.1.sh
- scripts/test_case_2.1.sh
- scripts/test_case_2.2.sh
- scripts/test_case_2.3.sh
- scripts/test_case_2.4.sh
- scripts/test_case_2.5.sh
- scripts/test_case_2.6.sh
- scripts/test_case_2.7.sh
- scripts/test_case_3.1.sh
- scripts/test_case_3.2.sh
- scripts/test_case_3.3.sh
- scripts/test_case_3.4.sh
- scripts/test_case_4.1.sh
- scripts/test_case_4.2.sh
- scripts/test_case_4.3.sh
- scripts/test_case_4.4.sh
- scripts/test_case_4.6.sh
- scripts/test_case_5.2.sh
> Ac 563 delete key page

- scripts/README.md
- scripts/cli_adi_create_account.sh
- scripts/cli_key_generate.sh
- scripts/fcttest.sh
- scripts/test_case_1.1.sh
- scripts/test_case_2.1.sh
- scripts/test_case_2.2.sh
- scripts/test_case_2.3.sh
- scripts/test_case_2.4.sh
- scripts/test_case_2.5.sh
- scripts/test_case_2.6.sh
- scripts/test_case_2.7.sh
- scripts/test_case_3.1.sh
- scripts/test_case_3.2.sh
- scripts/test_case_3.3.sh
- scripts/test_case_3.4.sh
- scripts/test_case_4.1.sh
- scripts/test_case_4.2.sh
- scripts/test_case_4.3.sh
- scripts/test_case_4.4.sh
- scripts/test_case_4.6.sh
- scripts/test_case_5.2.sh
> Ac 562 create an adi token account bound to a keybook

- scripts/README.md
- scripts/cli_adi_create_account.sh
- scripts/cli_key_generate.sh
- scripts/fcttest.sh
- scripts/test_case_1.1.sh
- scripts/test_case_2.2.sh
- scripts/test_case_2.3.sh
- scripts/test_case_2.4.sh
- scripts/test_case_2.5.sh
- scripts/test_case_2.6.sh
- scripts/test_case_2.7.sh
- scripts/test_case_3.1.sh
- scripts/test_case_3.2.sh
- scripts/test_case_3.3.sh
- scripts/test_case_3.4.sh
- scripts/test_case_4.1.sh
- scripts/test_case_4.2.sh
- scripts/test_case_4.3.sh
- scripts/test_case_4.4.sh
- scripts/test_case_4.5.sh
- scripts/test_case_4.6.sh
- scripts/test_case_4.7.sh
- scripts/test_case_5.2.sh
> Added test case 4.7 script

- cmd/cli/cmd/adi_test.go
- cmd/cli/cmd/faucet_test.go
- cmd/cli/cmd/page_test.go
- cmd/cli/cmd/root_test.go
- internal/testing/app_client.go
By changing the block frequency to ~10Hz
> Attempt to get the CLI tests running in CI

- internal/api/v2/types.yml
- internal/api/v2/types_gen.go
- internal/cmd/gentypes/main.go
- internal/cmd/gentypes/types.go
Update typegen to not `omitempty` for certain fields
> Fix AC-664

- cmd/cli/cmd/util.go
> fix: go1.16 compat

- cmd/accumulated/cmd_run.go
- cmd/accumulated/cmd_run_devnet.go
- cmd/accumulated/program.go
- internal/accumulated/run.go
- internal/accumulated/sentry.go
- networks/networks.go
Run all of the nodes of a local devnet in a single terminal, in a single process, with `accumulated run devnet`.
To verify, `accumulated init devnet && accumulated run devnet`.
> Run devnet in one process

- .gitlab-ci.yml
- cmd/accumulated/cmd_run_devnet.go
- cmd/cli/cmd/root.go
- cmd/cli/cmd/root_test.go
- cmd/cli/cmd/tx.go
- cmd/cli/cmd/util.go
- config/config.go
- debug/faucet_test.go
- internal/accumulated/run.go
- internal/api/jsonrpc_test.go
- internal/api/v2/error.go
- internal/api/v2/execute_test.go
- internal/api/v2/jrpc.go
- internal/api/v2/jrpc_execute.go
- internal/api/v2/jrpc_metrics.go
- internal/node/e2e_test.go
- internal/node/local_client.go
- internal/relay/client.go
- internal/relay/helper.go
- internal/relay/relay.go
- scripts/ci/devnet-deploy.sh
- scripts/ci/validate.sh
- scripts/matrix/build_cli.sh
- scripts/matrix/cli_create_id.sh
- scripts/matrix/ensure_api.sh
- scripts/matrix/test_case_1.1.sh
Fix CI validation and fix some bugs
> CI validation

- config/config.go
- internal/abci/utils_test.go
- internal/chain/chain.go
- internal/chain/executor.go
- internal/chain/executor_synthetic.go
- internal/chain/state.go
- internal/chain/synthetic_anchor.go
- internal/chain/synthetic_mirror.go
- internal/chain/txn_dispatch.go
- internal/chain/utils.go
- internal/genesis/bootstrap.go
- internal/logging/types.go
- internal/node/utils_test.go
- protocol/faucet.go
- protocol/protocol.go
- types/state/StateDB.go
Send mirror and anchor txns from the DN to BVNs
> Mirror and anchor from DN to BVNs

- internal/abci/e2e_test.go
- internal/abci/utils_test.go
- internal/api/v2/e2e_harness_test.go
- internal/api/v2/e2e_test.go
- internal/api/v2/jrpc_utils_test.go
- internal/api/v2/pack.go
- internal/api/v2/query_direct.go
- internal/api/v2/query_dispatch.go
- internal/chain/executor_query.go
- internal/chain/txn_dispatch.go
- internal/node/e2e_test.go
- internal/testing/e2e/suite.go
- internal/testing/e2e/tests.go
- internal/testing/state.go
Adds end-to-end test suite and a validation test
> Tests for API v2

- .dockerignore
- .gitlab-ci.yml
- Dockerfile
- Dockerfile.cli
- Makefile
- cmd/accumulated/cmd_init.go
- docs/Testing.md
- go.mod
- go.sum
- networks/networks.go
- scripts/ci/validate.sh
- Now you can use docker compose to run a network
- Now CI runs the validation script _before_ merge, using docker compose to deploy a testnet for the CI job
> Use docker compose for deploy and validation

- internal/testing/app_client.go
There is still at least one race condition for ABCI test shutdown: panic - send on closed channel, from app client SubmitTx. Hopefully this change will fix that issue.
> Attempt to fix shutdown race conditions

- cmd/cli/cmd/account_test.go
- cmd/cli/cmd/adi.go
- cmd/cli/cmd/book.go
- cmd/cli/cmd/data.go
- cmd/cli/cmd/util.go
- docs/Transactions.md
- internal/abci/e2e_proofs_test.go
- internal/abci/e2e_test.go
- internal/abci/utils_test.go
- internal/api/v2/e2e_test.go
- internal/chain/create_data_account.go
- internal/chain/create_identity.go
- internal/chain/create_key_book.go
- internal/chain/create_token_account.go
- internal/chain/executor.go
- internal/chain/synthetic_chain_create_test.go
- internal/chain/synthetic_create_chain.go
- internal/chain/update_key_page.go
- internal/testing/state.go
- scripts/matrix/test_case_3.1.sh
- scripts/matrix/test_case_3.2.sh
- scripts/matrix/test_case_3.3.sh
- scripts/matrix/test_case_4.8.sh
Remove remaining ssg and sigspec references
> chore: remove remaining sig spec references

- client/client.go
- cmd/cli/cmd/account.go
- cmd/cli/cmd/adi.go
- cmd/cli/cmd/book.go
- cmd/cli/cmd/credits.go
- cmd/cli/cmd/data.go
- cmd/cli/cmd/faucet.go
- cmd/cli/cmd/get.go
- cmd/cli/cmd/page.go
- cmd/cli/cmd/page_test.go
- cmd/cli/cmd/root.go
- cmd/cli/cmd/root_test.go
- cmd/cli/cmd/tx.go
- cmd/cli/cmd/util.go
- cmd/cli/cmd/version.go
- internal/api/v2/e2e_test.go
- push api to v2 in cli
- consolidated redundant code
- changed actor to origin
- fixed lingering sponsor reference in one of the tests
- misc cleanup
> Ac 659 update cli v2

- smt/storage/badger/db.go
Run GC on the badger DB every hour
> Run GC on badger

- smt/storage/badger/db.go
Changed the permissions from 0777 to 0700. Tried changing to 0600 but there were certain testcases failing however with 0700 everything seems to be working.
> AC-547 restricting database permissions

- cmd/accumulate/cmd/util.go
- internal/abci/e2e_test.go
- internal/abci/utils_test.go
- internal/api/unmarshal.go
- internal/chain/add_credits.go
- internal/chain/create_token_account.go
- internal/chain/executor_txn.go
- internal/chain/send_tokens.go
- internal/chain/synthetic_chain_create_test.go
- internal/chain/synthetic_deposit_tokens.go
- internal/testing/state.go
- protocol/TokenAccount.go
- protocol/TokenAccount_test.go
- protocol/chain.go
- protocol/types.yml
- protocol/types_gen.go
- types/api/response/TokenAccount.go
migration of TokenAccount to protocol package in types.yml file to be autogenerated
> AC 788 migrate TokenAccount to protocol package in types.yml

- cmd/accumulate/cmd/account.go
- cmd/accumulate/cmd/adi.go
- cmd/accumulate/cmd/util.go
- internal/abci/e2e_proofs_test.go
- internal/abci/e2e_test.go
- internal/api/jsonrpc.go
- internal/api/unmarshal.go
- internal/api/v2/api_gen.go
- internal/api/v2/e2e_test.go
- internal/api/v2/jrpc_execute.go
- internal/api/v2/methods.yml
- internal/api/v2/unmarshal.go
- internal/chain/create_identity.go
- internal/chain/create_token_account.go
- protocol/transaction.go
- protocol/types.yml
- protocol/types_gen.go
- types/api/APIRequests_test.go
- types/api/response/ADI.go
- types/api/response/AnonTokenAccount.go
- types/api/response/TokenAccount.go
- types/api/transactions/gentransaction_test.go
Consolidate transaction type switches used for unmarshalling transactions into a single function
> Consolidate transaction type switches

- cmd/accumulate/cmd/util.go
- internal/abci/e2e_test.go
- internal/chain/create_data_account.go
- internal/chain/create_identity.go
- internal/chain/create_key_book.go
- internal/chain/create_key_page.go
- internal/chain/create_token_account.go
- internal/chain/executor_query.go
- internal/chain/executor_txn.go
- internal/chain/synthetic_chain_create_test.go
- internal/chain/synthetic_create_chain.go
- internal/chain/update_key_page.go
- internal/genesis/bootstrap.go
- internal/testing/state.go
- types/state/chain_header.go
Change keybook data type from chainid to url string
> AC-720 chainheader keybook to url string
