- .gitignore
- README.md
- blockchain/accumulate/accnode.go
- blockchain/tendermint/abci-bvc.go
- blockchain/tendermint/abci-dbvc.go
- blockchain/tendermint/tendermint.go
- blockchain/validator/Node.go
- cmd/accumulated/cmd_run.go
- cmd/accumulated/cmd_testnet.go
- config/config.go
- go.mod
- go.sum
- networks/networks.go
- router/jsonrpc.go
- router/jsonrpc_test.go
- router/utils_test.go
**This should be merged after #19**
- Adds `package config` with a `Config` struct containing fields for accumulate-specific configuration
- Refactors `accumulated` to parse config once, passing around a config object instead of passing around the config path and parsing the config multiple times
- Refactors `accumulated` to use properties of the new `config.Config` type, instead of calling Viper directly
- Adds a subcommand, `accumulated testnet`, that generates a localhost testnet
I tested this with `TestLoadOnRemote` and it worked if I decreased the transaction rate. Otherwise I got network timeouts. I think my local machine just can't keep up.
> Localhost Testnet

- cmd/accumulated/cmd_testnet.go
- internal/node/init.go
- Reverts a change in the initialization code which results in `config.Consensus.CreateEmptyBlocks` always being set false (the default is true)
- Add a flag to the testnet subcommand to set `config.Consensus.CreateEmptyBlocks = false`, allowing easier testing (less log noise)
> Add `--no-empty-blocks` flag to testnet subcommand

- cmd/accumulated/cmd_testnet.go
- internal/node/init.go
**Before this is merged, #35 must be merged and `AC-287-tendermint-0.35` must be deleted.**
Adds the capability to initialize a local testnet with follower nodes in addition to validator nodes.
The key to getting validators and followers to work together is to ensure that the set of validators includes only validators. Specifically, `<dir>/config/genesis.json` has a `"validators"` array, and Tendermint expects every entry to correspond to a validator node. If one of the entries is actually a follower node, Tendermint consensus will wait for that node to sign proposals and votes, which won't happen (because followers don't sign), so consensus will stall.
I did not add any follower-mode capability to `accumulated init`, because it's not clear how that should work. That's something we should …
> Add capability to init testnet with followers

- cmd/accumulated/cmd_init.go
- cmd/accumulated/cmd_testnet.go
- go.mod
- go.sum
- internal/node/init.go
Implements `accumulated init follower` subcommand, which will initialize `~/.accumulate/Node0/` as a follower of the specified network. For example, `go run ./cmd/accumulated init follower -n EastXeons --listen tcp://127.0.2.1` will create a follower node that connects to EastXeons.
Doing it this way is potentially unsafe (I think?), because it fetches the genesis doc from the remote node. And since the genesis doc is defines the validators, a middleman or a malicious node could give you bad key info. If you run the command this way, it will warn you that you are pulling the genesis doc from the remote. You can also use a local copy of the genesis doc with the `--genesis` flag (this gets copied into the node's config dir).
I tested this with my localhost testnet (`-n Localhost`) and it …
> Follower node setup

- smt/storage/database/cache_test.go
- smt/storage/database/manager.go
- smt/storage/database/manager_test.go
- types/state/StateDB_test.go
As of Go 1.11, the compiler recognizes clear-map operations (`for k := range m { delete(m, k) }`) and optimizes away the loop. For batch sizes of 100 transactions, using a delete-loop is somewhat faster and reduces the GC pressure by an order of magnitude, as compared to recreating the map (`make(map[key]value, 100)`). The GC pressure difference for a batch size of 1000 is nearly two orders of magnitude. If the map is not preallocated (e.g. `make(map[key]val)` or `map[key]val`), the speed difference is larger.
> Optimize database manager TX cache

- cmd/accumulated/cmd_init.go
- config/config.go
- config/config_test.go
- router/jsonrpc.go
- router/utils_test.go
Fixes a bug in `package config` that prevented Accumulate's configuration from being loaded, leaving the API listen addresses blank. Adds a unit test that should detect any similar bugs in the future.
> Fix config loading

- cmd/accumulated/cmd_run.go
- internal/abci/abci.go
- internal/abci/accumulator.go
- internal/abci/e2e_test.go
- internal/api/utils_test.go
- internal/chain/manager.go
- types/api/transactions/gentransaction.go
- types/api/transactions/tokentransaction.go
- types/state/StateDB.go
Adds an end-to-end test of the ABCI application, in isolation from Tendermint. This is effectively the same as the load test, but done without starting the Tendermint node.
> End-to-end test of the ABCI application

- cmd/accumulated/cmd_init.go
- cmd/accumulated/cmd_loadtest.go
`accumulated init follower` and `accumulated loadtest` were broken by AC-347. This fixes it.
> Fix init follower and loadtest

- cmd/accumulated/cmd_loadtest.go
- cmd/accumulated/cmd_run.go
- internal/abci/e2e_test.go
- internal/api/jsonrpc.go
- internal/api/jsonrpc_test.go
- internal/api/query.go
- internal/api/query_test.go
- internal/api/testutils_test.go
- internal/api/utils2_test.go
- internal/api/utils_test.go
- internal/chain/manager.go
- internal/relay/relay.go
- internal/testing/load.go
Change relay.Relay to accept Tendermint transactions to allow for decoupling `relay.Relay`, `api.Query`, and `rpchttp.HTTP`. This will allow the relay and API to be tested independently, and will allow more flexibility and code reuse.
> Move query and transaction marshalling to api.Query

- Makefile
- cmd/accumulated/cmd_version.go
- internal/abci/accumulator.go
- version.go
Embeds version info, when built with `make`, which is exposed via `accumulated version` and via the `/abci_info` RPC call. This can be used to show which commit a given node is running.
> Embed version info

- internal/api/query.go
- internal/api/unmarshal.go
Factor out unmarshalling from `api.Query.Get*` into separate functions. In `api.Query.GetChainState`, use a switch statement to call the appropriate unmarshaller, instead of issuing a duplicate query.
> Do not double query

- types/state/ADI.go
- types/state/Chain.go
- types/state/Object.go
- types/state/Token.go
- types/state/TokenAccount.go
- types/state/Transaction.go
A number of types in `types` have an unused anonymous interface field. Because this field is never set, calling any of it's methods will cause a panic. Because the field is never referenced by anything, it should be removed. Because the interface type is never referenced by anything (except these fields), it should be removed.
In addition, a number of types contain an anonymous struct field that does not appear to serve a purpose, in that the fields might as well be included directly. Except for one case where the embedded type was referenced elsewhere, I moved the embedded type's field into the 'parent' type and removed the embedded type. The only side effect this will have is to make the 'parent' type's fields exported.
> Remove anonymous interface field

- internal/chain/adi.go
- internal/chain/anonymous_token.go
- internal/chain/block_validator.go
- internal/chain/manager.go
- internal/chain/synthetic_identity_create.go
- internal/chain/synthetic_transaction_deposit.go
- internal/chain/token_chain_create.go
- internal/chain/token_issuance.go
- internal/chain/token_transaction.go
- types/state/Chain.go
- types/state/Object.go
- Move state loading from chain.Manager to package state
- Add StateDB.LoadChain, which retrieves and unmarshals a chain
- Add StateDB.LoadChainADI, which retrieves and unmarshals a chain's ADI
- Add StateDB.LoadChainAndADI, which calls both of the above
- Rename StateEntry.IdentityState to AdiState
This also removes some (but not all) redundant state retrieval and unmarshalling.
> Clarify state loading

- types/api/ADI.go
- types/api/transactions/gentransaction_test.go
`api.ADI` encodes its TX type as an `int64`. It needs to be encoded as a `uint64`.
> Correctly encode ADI TX type

- internal/chain/anonymous_token.go
- internal/chain/synthetic_identity_create.go
- internal/chain/synthetic_transaction_deposit.go
- internal/chain/validator.go
`internal/chain.validator` distinguishes between create-identity and create-chain operations. This PR removes that distinction.
> Merge create-identity and create-chain

- internal/api/jsonrpc_test.go
- types/api/TokenAccount_test.go
- types/state/StateDB_test.go
- Adds `defer db.Close()` to state DB consistency test, because Windows gets upset if you don't do that.
- Adds `\n` after a print statement in a test so that VSCode can recognize that the test succeeded.
- Moves the skip in `TestJsonRpcAdi` to the beginning.
- Replaces `os.TempDir` call with `testing.T.TempDir` in `TestJsonRpcAdi`.
> Get tests working on Windows

- .github/workflows/validate.yml
- cmd/accumulated/cmd_loadtest.go
- cmd/accumulated/cmd_run.go
- internal/relay/client.go
- internal/relay/helper.go
- internal/relay/relay.go
Allows `relay.Relay` to accept any `rpc.ABCIClient` instead of restricting it to only `rpc/http.HTTP`. Batching will be transparently ignored for clients other than `rpc/http.HTTP`.
> Allow Relay to use any ABCI RPC client

- internal/abci/e2e_statedb_test.go
- internal/abci/e2e_test.go
- internal/abci/utils_test.go
- internal/api/jsonrpc_test.go
- internal/api/unmarshal.go
- internal/chain/adi.go
- internal/chain/anonymous_token.go
- internal/chain/synthetic_identity_create.go
- internal/chain/validator.go
- internal/testing/app_client.go
- internal/testing/state.go
- types/api/TokenTx.go
- types/api/transactions/gentransaction.go
- types/state/ADI.go
- types/state/ADI_test.go
- types/state/TokenAccount.go
- types/synthetic/AdiStateCreate.go
- types/synthetic/AdiStateCreate_test.go
- `chain.validator`: Add special case for anonymous tokens, use transaction type for all other transactions
- `chain.ADI`: Allow sponsor to be an anonymous token account
- `chain.SynIdentityCreate`: Unmarshal TX payload as `synthetic.AdiStateCreate` instead of `api.ADI`
- `chain.SynIdentityCreate`: Use `StateDB.AddStateEntry` instead of `DeliverTxResult.AddStateData`
- `chain.SynIdentityCreate`: Store chain as `state.AdiState` instead of `api.ADI`
- `synthetic.AdiStateCreate`: Fix bug in unmarshalling
> Basic ADI creation

- internal/testing/load.go
I added a change that forces signature validation failures to test error reporting, and I forgot to remove it.
> Remove test code (fix load test)

- .gitlab-ci.yml
- Makefile
Deploy `accumulated` binary to each server continuously from `develop` (whenever a commit is pushed to `develop`)
> Continuously deploy binary

- .gitignore
- cmd/accumulated/cmd_loadtest.go
- cmd/cli/cmd/tx.go
- internal/abci/utils_test.go
- internal/api/jsonrpc.go
- internal/api/jsonrpc_test.go
- internal/api/query.go
- internal/api/unmarshal.go
- internal/relay/relay.go
- types/api/TokenTx.go
- decoupled query by url and txid
- added query by txid (i.e. transaction hash) only
- added query by chainId (currently internal-only)
> Ac 284 support for transactions hash

- .github/workflows/validate.yml
- cmd/accumulated/cmd_loadtest.go
- internal/abci/accumulator.go
- internal/api/jsonrpc.go
- internal/api/jsonrpc_test.go
- internal/api/query.go
- internal/chain/executor.go
- internal/relay/client.go
- internal/relay/helper.go
- internal/relay/relay.go
- internal/testing/app_client.go
- internal/testing/load.go
- types/api/APIRequests.go
Adds support to `relay.Relay` for starting up the websocket RPC client and subscribing to TX results. Adds `SubscribeTx` for subscribing to the results of DeliverTx for a particular transaction. Adds `GetTx` to relay, which calls `rpcclient.Tx`. Adds corresponding methods to `api.Query`. Adds a parameter to `BroadcastTx` that can be used to wait for DeliverTx results for that transaction. Updates load test to wait for TX results before continuing.
> Track DeliverTx results (2/4)

- .gitignore
- cmd/cli/cmd/tx.go
- internal/api/jsonrpc.go
- internal/api/jsonrpc_test.go
- internal/api/utils_test.go
- internal/chain/assign_sig_spec_group.go
- internal/chain/create_sig_spec_group.go
- internal/chain/executor.go
- internal/chain/identity_create.go
- internal/testing/load.go
- internal/testing/state.go
- internal/url/url.go
- protocol/hash_algorithm.go
- protocol/keys.go
- types/TransactionTypes.go
- types/api/APIRequests.go
- types/api/transactions/SignatureInfo.go
- types/api/transactions/gentransaction_test.go
- types/state/Transaction_test.go
Validate transaction signatures against the transaction sponsor's sig group, for all transactions.
> Validate against sponsor's sig group (4/4)

- cmd/accumulated/cmd_config.go
- cmd/accumulated/cmd_init.go
- cmd/accumulated/cmd_loadtest.go
- cmd/accumulated/cmd_run.go
- cmd/accumulated/cmd_service.go
- cmd/accumulated/cmd_testnet.go
- cmd/accumulated/main.go
- cmd/accumulated/program.go
- cmd/accumulated/tendermint_logger.go
- go.mod
- go.sum
- internal/abci/accumulator.go
- internal/abci/accumulator_test.go
- internal/abci/e2e_test.go
- internal/abci/utils_test.go
- internal/api/jsonrpc_test.go
- internal/api/query.go
- internal/chain/synthetic_token_deposit_test.go
- internal/node/init.go
- internal/node/node.go
- internal/relay/relay.go
- internal/testing/load.go
- internal/testing/node.go
- smt/storage/database/manager.go
- Add support for installing and running as a mac/windows/linux service.
- Cleans up error handling in `cmd/accumulated`
- Custom logging, to feed logs to the service system
It should be noted that in Windows, stdout/stderr of a service is not captured. In Windows, if logs are not written to the service logger, they may as well not exist. Logs written to the service logger are visible in the event viewer, but everything else goes into a void.
> Run as a service

- internal/api/utils_test.go
- smt/storage/database/manager.go
The method had a non-pointer receiver, so the caller's AppID never got set. Plus, it was reusing the slice, which could result in the various managers reusing the same underlying slice.
> Fix database.Manager.SetAppID

- internal/abci/accumulator_test.go
- internal/api/jsonrpc.go
- internal/chain/README.md
- internal/chain/_token_issuance.go
- internal/chain/add_credits.go
- internal/chain/chain.go
- internal/chain/create_sig_spec.go
- internal/chain/create_sig_spec_group.go
- internal/chain/executor.go
- internal/chain/identity_create.go
- internal/chain/state.go
- internal/chain/synthetic_create_chain.go
- internal/chain/synthetic_deposit_credits.go
- internal/chain/synthetic_token_deposit.go
- internal/chain/synthetic_token_deposit_test.go
- internal/chain/token_account_create.go
- internal/chain/token_transaction.go
- internal/chain/token_transaction_test.go
- internal/testing/load.go
- internal/testing/state.go
- types/state/Chain.go
- types/state/Object.go
- types/synthetic/TokenTransactionDeposit.go
- types/synthetic/TokenTransactionDeposit_test.go
- Remove `state.StateEntry`
- Remove `chain.DeliverTxResult`
- Add `chain.StateManager`
- Loads chains, with a cache
- Unmarshals loaded chains by type
- Tracks pending writes
- Tracks pending synthetic transactions
- Update executor
- Execute pending writes on success
- Execute pending synthetic transactions on success
> Refactor chain validator state management

- internal/chain/identity_create.go
- internal/chain/synthetic_create_chain.go
- internal/chain/token_account_create.go
Ensure that chains are always added to a key book when they are created. Except lite accounts and unbound key pages.
> Ensure chains always have a key book

- internal/abci/e2e_test.go
- internal/abci/utils_test.go
- internal/chain/create_sig_spec.go
- internal/chain/create_sig_spec_group.go
- internal/chain/state.go
- internal/chain/synthetic_create_chain.go
- internal/cmd/gentypes/main.go
- protocol/transaction.go
- protocol/types.yml
- protocol/types_gen.go
- protocol/utils.go
Updates synthetic chain create so the caller has to specify if a chain is being created or updated, and SCC will fail if the chain does/does not exist (respectively).
> fix: check for existing ADI

- internal/chain/update_key_page.go
- internal/chain/update_key_page_test.go
- types/api/transactions/gentransaction.go
Ensure that a key page cannot modify key pages of a higher priority than itself
> fix: enforce key page priority rules

- internal/api/jsonrpc_test.go
- internal/chain/executor.go
- internal/url/url.go
Add support to `chain.Executor.Query` for querying transactions by URL with `?txid=...`
> feat: query by txid

- cmd/cli/cmd/root.go
Set the default server for the CLI to `https://testnet.accumulatenetwork.io/v1`
> CLI: set default server to testnet

- go.mod
- go.sum
- internal/testing/app_client.go
Fixes a bug where tests panic because Subscribe returns nil after the node is stopped
> fix: handle nil sub after node stop

- internal/abci/e2e_test.go
- internal/abci/utils_test.go
- internal/node/e2e_test.go
- internal/node/utils_test.go
- internal/testing/app_client.go
- internal/testing/e2e/suite.go
- internal/testing/state.go
- smt/storage/database/manager.go
Add true end-to-end tests of the Tendermint node + ABCI application, plus `api.Query` and `relay.Relay`/
> Use the same end-to-end suite for Tendermint node and ABCI application

- cmd/cli/cmd/account.go
- cmd/cli/cmd/adi.go
- cmd/cli/cmd/book.go
- cmd/cli/cmd/credits.go
- cmd/cli/cmd/faucet.go
- cmd/cli/cmd/get.go
- cmd/cli/cmd/page.go
- cmd/cli/cmd/root.go
- cmd/cli/cmd/tx.go
- cmd/cli/cmd/util.go
- added human readable output for book / page /adi / lite account create / update / query, including tx create.
- changed book and page create to use older json-rpc command to be compatible with deployed testnet.
- will humanize tx queries in later task
- will add unit tests in later task
> Ac 474 human readable output for cli

- internal/chain/add_credits.go
- internal/chain/chain.go
- internal/chain/create_identity.go
- internal/chain/create_key_book.go
- internal/chain/create_key_page.go
- internal/chain/create_token_account.go
- internal/chain/executor.go
- internal/chain/synthetic_chain_create_test.go
- internal/chain/synthetic_create_chain.go
- internal/chain/synthetic_deposit_credits.go
- internal/chain/synthetic_token_deposit.go
- internal/chain/synthetic_token_deposit_test.go
- internal/chain/withdraw_tokens.go
- internal/chain/withdraw_tokens_test.go
Simplifies the chain validators by merging CheckTx and DeliverTx into Validate. This is feasible since pending state changes and synthetic transactions are not sent until the transaction succeeds. Thus, CheckTx can use Validate and simply discard the pending changes.
This makes no functional changes.
> Simplify chain validators

- cmd/accumulated/cmd_init.go
Updates `accumulated init` to use the correct default configuration.
To verify, run `accumulated init` and verify that `accumulate.toml` contains `prometheus-server = "http://18.119.26.7:9090"`. For example, `go run ./cmd/accumulated init -n Zion -r Zion`.
> fix: node configuration

- CONTRIBUTING.md
Document that we should use the conventional commit standard.
No functional changes.
> docs: commit messages

- cmd/cli/cmd/book.go
- internal/api/jsonrpc.go
- internal/api/jsonrpc_test.go
- internal/api/query.go
- internal/api/unmarshal.go
- internal/api/v2/unmarshal.go
- internal/chain/add_credits.go
- internal/chain/create_key_book.go
- internal/chain/create_key_page.go
- internal/chain/executor.go
- internal/chain/state.go
- internal/chain/synthetic_chain_create_test.go
- internal/chain/synthetic_create_chain.go
- internal/chain/synthetic_deposit_credits.go
- internal/chain/synthetic_token_deposit.go
- internal/chain/synthetic_token_deposit_test.go
- internal/chain/update_key_page.go
- internal/chain/withdraw_tokens.go
- internal/cmd/gentypes/main.go
- internal/genesis/acme.go
- internal/node/e2e_test.go
- protocol/types.yml
- protocol/types_gen.go
- types/chain_types.go
- types/state/ADI.go
- types/state/Chain.go
- types/state/Chain_test.go
- types/state/Object_test.go
- types/state/Token.go
- Updates out-of-date chain types.
- Anon token account => lite token account
- Sig spec group => key book
- Sig spec => key page
- Renames `ChainTypeAdi` to `ChainTypeIdentity` so that it matches `TxTypeCreateIdentity`
- Updates chain type JSON marshalling
- `ChainTypeTokenAccount` now marshals to `"tokenAccount"` instead of `"ChainTypeTokenAccount"`
The only functional change is to the JSON marshalling of chain types.
> chore: rename chain types

- internal/api/v2/jrpc_query.go
Returns an error if count is zero.
To validate, run a local node and execute:
```shell
curl -X POST --data '{ "jsonrpc": "2.0", "id": 0, "method": "query-tx-history", "params": { "url": "e7ebdb79f46fd8f902f38b9bc8bc0d14906139a024cb1836/ACME" } }' -H 'content-type:application/json;' http://127.0.1.1:26660/v2
```
This should result in:
```json
{"jsonrpc":"2.0","error":{"code":-32802,"message":"Validation Error","data":"count must be greater than 0"},"id":0}
```
> fix: return an error if count is zero

- docs/Records.md
- docs/Transactions.md
- internal/chain/README.md
- internal/chain/burn_tokens.go
- internal/chain/create_data_account.go
- internal/chain/issue_tokens.go
- internal/chain/state.go
- internal/chain/synthetic_burn_tokens.go
- internal/chain/synthetic_write_data.go
- internal/chain/write_data.go
- internal/chain/write_data_to.go
- protocol/types.yml
- protocol/types_gen.go
- types/chain_types.go
- types/transaction_types.go
Adds most of the remaining chain and transaction types and stubs out the corresponding transaction validators.
No functional changes (since none of the transactions can actually be executed).
> feat: stub out remaining TXs and chains

- internal/abci/e2e_proofs_test.go
- internal/abci/e2e_statedb_test.go
- internal/abci/e2e_test.go
- internal/abci/utils_test.go
- internal/api/unmarshal.go
- internal/api/v2/jrpc.go
- internal/api/v2/jrpc_execute.go
- internal/chain/acme_faucet.go
- internal/chain/chain.go
- internal/genesis/faucet.go
- protocol/types.yml
- protocol/types_gen.go
- types/transaction_types.go
Adds an ACME faucet TX and adds a faucet method to API v2.
Test with `curl -X POST --data '{ "jsonrpc": "2.0", "id": 0, "method": "faucet", "params": { "url": "..." } }' -H 'content-type:application/json;' http://127.0.1.1:26660/v2`. Fill in the URL with your lite account address. Verify with `cli account get ...` and `cli tx history 7117c50f04f1254d56b704dc05298912deeb25dbc1d26ef6/ACME 0 10` (faucet history).
> feat: faucet TX and api v2

- cmd/cli/cmd/get.go
- added guard for args
"./cli get" caused a crash.
to confirm it doesn't crash and instead dumps out usage type:
./cli get
> fix: add guard for number of args

- internal/chain/state.go
Make `internal/chain.StateManager` more readable. No functional changes.
To the reviewer(s): If you have difficulty following any of the methods, please let me know so I can make this actually readable.
> chore: improve state manager readability

- cmd/cli/cmd/tx.go
- cmd/cli/cmd/util.go
- cleaned up human-readable output for tokenTx and syntheticTokenDeposit
output can be viewed by 
mishmash of receive and send token transactions
./cli tx history acc://7117c50f04f1254d56b704dc05298912deeb25dbc1d26ef6/ACME 0 10
receive tokens transaction example:
./cli tx get a5bea9be9885c5b71e8018f4391ea669d9b49bc41766e8b5f38e44b4c0abb720
send tokens transaction example:
./cli tx get 494aee6c6e7129450dd6086d720443592411673a22b05422325775ff77a1eb3c
> chore: Ac 519 tx output

- internal/api/v2/jrpc_metrics.go
- internal/api/v2/jrpc_query.go
- internal/api/v2/types.yml
- internal/api/v2/types_gen.go
Use txid/chainId for TX/chain queries instead of id.
Verify with `curl -X POST --data '{ "jsonrpc": "2.0", "id": 0, "method": "query-tx", "params": { "txid": "'${TXID}'" } }' -H 'content-type:application/json;' http://127.0.1.1:26660/v2`.
> chore(api/v2): replace id with txid/chainid

- internal/api/v2/unmarshal.go
Fix API v2 so it can unmarshal acme faucet transactions.
Verify with:
```
curl -X POST --data '{ "jsonrpc": "2.0", "id": 0, "method": "faucet", "params": { "url": "'${YOUR_LITE_ACCOUNT}'" } }' -H 'content-type:application/json;' http://127.0.1.1:26660/v2
curl -X POST --data '{ "jsonrpc": "2.0", "id": 4, "method": "query-tx-history", "params": { "url": "acc://7117c50f04f1254d56b704dc05298912deeb25dbc1d26ef6/ACME", "count": 20 } }' -H 'content-type:application/json;' http://127.0.1.1:26660/v2
```
> fix(api/v2): unmarshal acme faucet TXs

- internal/node/node_test.go
- internal/testing/node.go
The [`actually-close-databases` branch of our Tendermint fork](https://github.com/AccumulateNetwork/tendermint/tree/actually-close-databases) fixes issues with Tendermint not cleaning up after itself. Accumulate is already using a more recent version from the fork (branch `fix-rpc-event-sub-again`), so no go.mod changes are necessary.
I updated one of the tests to verify that no files remain open once the node is closed. This uses `/proc/<pid>/fd`, so it's a Linux-only thing.
> fix: cleanup tendermint databases

- types/chain_types.go
- chainMax not set correctly
- moved chainMax to a location where it is less likely to be missed when adding new types
- included chainMax when initializing the chainByName so that the last type can be unmarshaled with json
> fix: corrected issue with chainByName not setting last enumeration in list

- smt/managed/blockIndex.go
- smt/managed/hash.go
- smt/managed/hash_test.go
- smt/managed/merklemanager.go
- smt/managed/merklemanager_test.go
- smt/managed/merklemanagerrange_test.go
- smt/managed/merklemanagerrestart_test.go
- smt/managed/merklestate.go
- smt/managed/merklestate_test.go
- smt/managed/receipt.go
- smt/managed/receipt_test.go
- smt/storage/database/manager.go
- smt/storage/database/manager_test.go
- smt/storage/keys.go
- types/state/StateDB.go
Allow merkle trees to contain data that is not 32-bytes wide.
No functional changes. Verify that nothing breaks.
> feat(smt): support non-hash data in merkle trees

- internal/api/v2/query_direct.go
The explorer wants `count` to be passed through from the request to the response, unchanged.
> pass the count through

- internal/chain/executor.go
- internal/chain/executor_query.go
This is a simple copy-paste operation that moves `internal/chain.Executor.Query` and friends into their own file. Since querying and executing transactions are different operations, I think this will make it easier for developers to find what they're looking for.
No functional changes. To verify, check that the functions are identical and that queries still work (e.g. `cli adi get ...`).
> chore(chain): move queries to their own file

- cmd/accumulated/cmd_init.go
- cmd/accumulated/cmd_loadtest.go
- cmd/accumulated/program.go
- config/config.go
- config/config_test.go
- internal/abci/utils_test.go
- internal/api/utils_test.go
- internal/chain/chain.go
- internal/node/init.go
- internal/node/node_test.go
- internal/node/utils_test.go
- internal/testing/node.go
- networks/get.go
- networks/networks.go
Implements a directory node stub, plus corresponding configuration and initialization changes.
To verify:
- `accumulated init -n DevNet.Zion` - works as usual, `accumulate.toml` specifies `directory = "DevNet.Directory"`
- `accumulated init -n DevNet.Directory` - four nodes, two validators and two followers, `accumulate.toml` specifies `type = "directory"`
- `accumulated init devnet` - creates a local devnet with a DN and one BVN
> Directory node stub

- internal/abci/e2e_test.go
If a transaction is signed by a lite account or key page (so the nonce should be updated), unless that record itself was changed, the height of the chain must not change.
> test: verify that signator chain height is constant

- cmd/accumulated/cmd_init.go
- internal/abci/abci.go
- internal/abci/accumulator.go
- internal/abci/accumulator_test.go
- internal/abci/e2e_test.go
- internal/chain/executor.go
- internal/mock/abci/abci.go
- internal/node/init.go
- internal/node/utils_test.go
- internal/testing/node.go
- smt/storage/memory/db.go
- types/state/StateDB.go
Updates node setup and ABCI chain initialization to preload the database. Node setup initializes a `memory.DB` and marshals it, saving it as the app state in the genesis document. ABCI chain initialization loads the app state (from the genesis doc) and pushes it into the database.
This will allow us to add arbitrary state to the node database during setup by directly manipulating the `memory.DB` and executing transactions. Right now, all it does is set "ChainID".
To verify, setup and launch a node, then stop it, then restart it. Verify that one of the startup messages is `Starting ABCI ... chain=<chainId> module=accumulate`. Previously, `chain=...` only appeared the first time the node was launched, as the chain ID was set by InitChain, which is only called the first time the node …
> Add basic genesis app state to genesis doc

- .gitlab-ci.yml
- cmd/accumulated/cmd_init.go
- config/config.go
- internal/node/init.go
- scripts/ci/devnet-deploy.sh
- Moves CI deployment script into its own file, for (relative) ease of testing
- Tweaks `accumulated init` to allow for disabling the website
- Updates CI to deploy configuration to `~/.accumulated/bvn` instead of `~/.accumulated/Node#`
- Updates CI to not delete `~/.accumulated` and write logs to `~/.accumulated/logs`
- Updates CI to deploy DevNet DN
> ci: deploy DN to DevNet

- client/client.go
- cmd/cli/cmd/tx.go
- cmd/cli/cmd/util.go
- internal/abci/accumulator.go
- internal/api/v2/jrpc.go
- internal/api/v2/jrpc_execute.go
- internal/api/v2/jrpc_utils.go
- internal/api/v2/types.yml
- internal/api/v2/types_gen.go
- internal/cmd/gentypes/main.go
- protocol/types_gen.go
- types/state/types_gen.go
- Fix ABCI error reporting
- Fix JSON unmarshaling of API v2 TxRequest when the Payload field is set
- Fix unmarshalling and validating for API v2 execute methods
- Fix issue where setting the key page index to 0 would result in validation errors
- Migrate cli tx create to API v2
To validate, run `cli -d tx create ${SENDER} ${RECIPIENT} ${AMOUNT}` and verify that the server URL ends in /v2 and the transaction succeeds.
> Migrate CLI tx create to API v2

- cmd/cli/cmd/root.go
- cmd/cli/cmd/util.go
Add a flag to the CLI that sets `checkOnly` for API v2 transaction requests. For CLI commands that have been migrated to API v2, this will validate the transaction without submitting it.
To verify, run `cli tx create ${SENDER} ${RECIPIENT} ${AMOUNT}` and verify that it worked (`cli account get ${RECIPIENT}`). Then send `cli tx create --pretend ...` and verify that the request succeded, but the recipient account balance did not change.
> Add a --pretend flag to the CLI

- cmd/accumulated/program.go
- config/config.go
- internal/abci/accumulator.go
- internal/abci/e2e_statedb_test.go
- internal/abci/utils_test.go
- internal/chain/chain.go
- internal/chain/executor.go
- internal/chain/synthetic_chain_create_test.go
- internal/chain/synthetic_token_deposit_test.go
- internal/chain/update_key_page_test.go
- internal/chain/withdraw_tokens_test.go
- internal/logging/console.go
- internal/logging/filter.go
- internal/node/init.go
- internal/node/node.go
- internal/testing/node.go
- smt/managed/merklemanager_test.go
- smt/managed/merklemanagerrange_test.go
- smt/managed/merklemanagerrestart_test.go
- smt/managed/receipt_test.go
- smt/pmt/manager_test.go
- smt/storage/badger/db.go
- smt/storage/database/manager.go
- smt/storage/database/manager_test.go
- smt/storage/keyvaluedb.go
- smt/storage/memory/db.go
- smt/storage/memory/db_test.go
- types/state/StateDB.go
Adds per-module log filtering and updates everything to use the same logger.
To verify, run a node and observe far fewer log messages.
> Log filtering

- .github/workflows/lint.yml
- cmd/cli/cmd/tx.go
- internal/testing/load.go
- smt/managed/receipt_test.go
- types/api/TokenTx.go
- types/state/Transaction_test.go
Fixes `go vet ./...` warnings and adds `go vet ./...` to CI.
Fixes #291
> Add go vet to CI

- internal/chain/executor_query.go
- types/state/StateDB.go
- types/state/StateDB_test.go
Update `StateDB.GetChainRange` to work if the specified range crosses a mark point.
> Fetch TX history across mark points

- .gitlab-ci.yml
This makes no functional changes. It creates a job template that makes it easier to create additional validation jobs.
> ci: make a template for validation jobs

- internal/chain/executor.go
- smt/storage/memory/db.go
InitChain loads state from the genesis doc (AC-622, AC-632). However, the BPT root hash does not get updated. This PR adds a call to `StateDB.Load` to reload the BPT from the database. It also adds a sanity check.
To verify, create and launch a BVN node, wait for it to settle, stop it, and restart it. On `develop` this will fail. With this PR, it will not fail.
> fix: reload state DB after loading genesis state

- internal/abci/e2e_test.go
- internal/chain/add_credits.go
- protocol/protocol.go
We need to be able to charge fees down to 1/100th of a cent. The simplest way to do this is to change the conversion rate to 1 dollar = 10,000 credits.
> chore: update credit to dollar conversion rate

- cmd/accumulated/program.go
- cmd/cli/cmd/account_test.go
- cmd/cli/cmd/adi_test.go
- cmd/cli/cmd/faucet_test.go
- cmd/cli/cmd/page_test.go
- cmd/cli/cmd/root_test.go
- cmd/cli/cmd/tx.go
- cmd/cli/cmd/util.go
- config/config.go
- go.mod
- internal/abci/accumulator.go
- internal/api/v2/jrpc_query.go
- internal/api/v2/pack.go
- internal/api/v2/query.go
- internal/api/v2/query_direct.go
- internal/api/v2/query_dispatch.go
- internal/api/v2/types.go
- internal/api/v2/types.yml
- internal/api/v2/types_gen.go
- internal/api/v2/unmarshal.go
- internal/mock/api/types.go
- internal/testing/e2e/tests.go
- internal/testing/node.go
- Add `wait` parameter to API v2 `query-tx`, which will poll every half second for the TX status, for up to 10 seconds (configurable)
- Add `--wait` to `cli tx get`, which is passed to `query-tx` as `wait`
- Add `--wait-synth` to `cli tx get`, which will iterate over the transaction's synthetic transactions, if any, and `query-tx` each one, with `wait`
> Wait for TX to complete

- internal/abci/e2e_statedb_test.go
If badger is closed first, there's a race condition where the ABCI app client might attempt to read from badger after it's closed. Waiting until test cleanup to close badger should avoid this.
> test: close badger after stopping the ABCI

- internal/chain/executor_query.go
- internal/cmd/getchain/getchain.go
Fix the executor's implementation of query by chain ID.
Verify with `curl -s -X POST --data '{ "jsonrpc": "2.0", "id": 0, "method": "query-chain", "params": { "chainId": "'${CHAIN}'" } }' -H 'content-type:application/json;' ${SERVER}`
> Fix query by chain ID

- cmd/accumulated/cmd_init.go
- cmd/accumulated/program.go
- cmd/cli/cmd/root_test.go
- internal/abci/e2e_proofs_test.go
- internal/abci/e2e_statedb_test.go
- internal/abci/e2e_test.go
- internal/abci/utils_test.go
- internal/api/jsonrpc_test.go
- internal/api/utils_test.go
- internal/chain/chain.go
- internal/chain/executor.go
- internal/chain/executor_query.go
- internal/chain/txn_dispatch.go
- internal/chain/utils.go
- internal/logging/test.go
- internal/node/e2e_test.go
- internal/node/node.go
- internal/node/node_test.go
- internal/node/utils_test.go
- internal/relay/helper.go
- internal/testing/node.go
- internal/testing/tx.go
- networks/get.go
Creates a new transaction dispatcher. The new dispatcher:
- Uses batch RPC calls, so all synthetic transactions are still broadcast in a single request.
- Uses a local RPC client for synthetic transactions destined for the local node, which does not create a network connection.
- Knows how to route system records such as `acc://dn` or `acc://bvn-...` directly to the correct network, circumventing the normal routing method.
With this change, the relay is no longer used outside of the API and can be removed once API v1 is removed.
Updates `accumulated init devnet` to support creating a multi-BVN devnet.
No functional changes. To verify, create a multi-BVN devnet, run it, and make sure the normal things work.
> Transaction dispatcher (for the transaction executor)

- internal/chain/chain.go
- internal/chain/executor.go
- internal/chain/executor_synthetic.go
- internal/chain/synthetic_anchor.go
- internal/chain/utils.go
- internal/testing/app_client.go
- protocol/types.yml
- protocol/types_gen.go
- types/state/StateDB.go
- types/state/anchor_chain.go
- types/state/index.go
- types/state/stateTxn.go
- types/state/synth_chain.go
- types/state/system_chains.go
- types/state/types.yml
- types/state/types_gen.go
- types/transaction_types.go
At the beginning of block N+1, if block N made changes, the BVN builds a synthetic transaction containing various anchors and sends it to the DN.
> BVN anchor → DN

- internal/api/unmarshal.go
- internal/api/v2/query_direct.go
- internal/api/v2/unmarshal.go
- internal/chain/state.go
- protocol/chain.go
Consolidates unmarshalling of chains, so that there's only one switch-on-chain-type instead of three.
No functional changes. To verify, run a devnet and test it.
> Consolidate chain unmarshalling

- internal/accumulated/run.go
- internal/api/v2/jrpc.go
- internal/api/v2/types.yml
- internal/chain/chain.go
- internal/chain/executor.go
- internal/chain/executor_query.go
- internal/chain/executor_synthetic.go
- internal/chain/executor_utils.go
- internal/chain/state.go
- internal/chain/synthetic_mirror.go
- internal/genesis/bootstrap.go
- internal/node/utils_test.go
- protocol/types.yml
- protocol/types_gen.go
- types/state/anchor_chain.go
- types/state/types.yml
- types/state/types_gen.go
- types/transaction_types.go
Mirrors the BVN ADIs to the DN.
To verify, start a local devnet, wait for it to settle, then run `curl -s -X POST --data '{ "jsonrpc": "2.0", "id": 0, "method": "debug-query-direct", "params": { "url": "bvn-DevNet.BVN0/validators0" } }' -H 'content-type:application/json;' ${SERVER}` against the DN to verify that the DN has the BVN's keys.
> Mirror BVN ADIs to DN

- internal/chain/executor.go
- internal/chain/executor_synthetic.go
- internal/chain/state.go
- internal/genesis/bootstrap.go
- smt/managed/blockIndex.go
- smt/managed/merklemanager.go
- smt/managed/merklemanager_test.go
- smt/managed/merklemanagerrange.go
- smt/managed/merklemanagerrange_test.go
- smt/pmt/manager.go
- smt/storage/database/manager.go
- smt/storage/database/manager_test.go
- smt/storage/keys.go
- types/state/StateDB.go
- types/state/StateDB_test.go
- types/state/chain_manager.go
- types/state/index.go
Stop using `key ...interface{}` and `key []interface{}` and instead pass around `key storage.Key`. Adds `func (Key) Append(...interface{}) Key` for convenience. Also, keys are calculated with H(H(H(v1)+v2)+v3) instead of H(v1 + v2 + v3).
> Refactor DB keys

- internal/api/jsonrpc.go
The transaction type check is using out of date transaction type names. API v1 is deprecated, so I just removed the check.
> fix: API v1 token-tx

- cmd/cli/cmd/tx.go
- cmd/cli/cmd/util.go
- internal/api/jsonrpc.go
- internal/api/jsonrpc_test.go
- internal/api/unmarshal.go
- internal/api/v2/jrpc.go
- internal/api/v2/pack.go
- internal/api/v2/unmarshal.go
- internal/chain/chain.go
- internal/chain/send_tokens.go
- internal/chain/send_tokens_test.go
- internal/testing/load.go
- protocol/fee_schedule.go
- types/api/APIRequests_test.go
- types/api/TokenTx.go
- types/api/TokenTx_test.go
- types/api/response/TokenTx.go
- types/state/Transaction_test.go
- types/transaction_types.go
For clarity. No functional changes, everything should still work the same, except the type for token transactions is now 'sendTokens'.
> Rename withdraw tokens txn to send tokens

- internal/api/v2/e2e_test.go
- internal/logging/tendermint.go
Sometimes a panic occurs in a log call. So I added something to make sure that doesn't crash the node.
[crash.txt](https://github.com/AccumulateNetwork/accumulate/files/7731246/crash.txt)
> fix: catch panic while logging

- .github/workflows/validate.yml
- .gitlab-ci.yml
- cmd/cli/cmd/root_test.go
- debug/faucet_test.go
- go.mod
- go.sum
- internal/abci/e2e_statedb_test.go
- internal/api/jsonrpc_test.go
- internal/api/v2/e2e_test.go
- internal/node/e2e_test.go
- internal/node/node_test.go
- internal/testing/skip.go
- internal/testing/tx.go
- smt/storage/badger/db.go
- smt/storage/keyvaluedb.go
- smt/storage/memory/db.go
- tools.go
- types/api/APIRequests_test.go
Use `gotest.tools/gotestsum` to run tests and generate a JUnit test report file. This will improve the readability of test results in CI, and GitLab CI can use the JUnit report to populate a test results UI.
> CI test reports

- internal/api/v2/e2e_test.go
One of the tests is failing to compile on `develop`, due to how PR merges occurred. This fixes the broken test.
> test: fix tests broken by merge

- cmd/cli/cmd/util.go
Eliminates a cast by strongly-typing a parameter.
> chore: avoid cast

- internal/testing/app_client.go
Fixes the ocassional panic in tests due to a race condition in `testing.ABCIApplicationClient`.
> fix: race condition

- cmd/cli/cmd/faucet_test.go
- cmd/cli/cmd/root.go
- cmd/cli/cmd/root_test.go
- cmd/cli/cmd/util.go
- internal/api/jsonrpc_test.go
- internal/api/utils2_test.go
- internal/api/utils_test.go
- internal/api/v2/e2e_harness_test.go
- internal/api/v2/e2e_test.go
- internal/node/e2e_test.go
- internal/node/node_test.go
- internal/node/utils_test.go
- internal/testing/ip.go
- internal/testing/node.go
Instead of hard coding IPs, test IPs are now derived from the SHA-256 hash of the file name and line number of the test.
> test: stop hard coding IPs
